export type Character = {
  id: number;
  image_url: string;
  name: string;
  gender: 'Homme' | 'Femme';
  race: string[];
  affiliation: string;
  abilities: string[];
  position: string;
  introduction_arc: string;
};

export const characters: Character[] = [
  {
    id: 1,
    image_url: '',
    name: 'Ichigo Kurosaki',
    gender: 'Homme',
    race: ['Humain', 'Shinigami', 'Hollow', 'Quincy'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai', 'Hollowfication', 'Fullbring'],
    position: 'Aucune',
    introduction_arc: 'Agent of the Shinigami',
  },
  {
    id: 2,
    image_url: '',
    name: 'Rukia Kuchiki',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '13ème Division',
    introduction_arc: 'Agent of the Shinigami',
  },
  {
    id: 3,
    image_url: '',
    name: 'Renji Abarai',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '6ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 4,
    image_url: '',
    name: 'Byakuya Kuchiki',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '6ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 5,
    image_url: '',
    name: 'Tōshirō Hitsugaya',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '10ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 6,
    image_url: '',
    name: 'Kenpachi Zaraki',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '11ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 7,
    image_url: '',
    name: 'Sōsuke Aizen',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: "Armée d'Aizen",
    abilities: ['Shikai', 'Hōgyoku'],
    position: '5ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 8,
    image_url: '',
    name: 'Gin Ichimaru',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: "Armée d'Aizen",
    abilities: ['Shikai', 'Bankai'],
    position: '3ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 9,
    image_url: '',
    name: 'Uryū Ishida',
    gender: 'Homme',
    race: ['Quincy', 'Humain'],
    affiliation: 'Karakura',
    abilities: ['Letzt Stil', 'Vollständig', 'Schrift'],
    position: 'Sternritter A',
    introduction_arc: 'Agent of the Shinigami',
  },
  {
    id: 10,
    image_url: '',
    name: 'Orihime Inoue',
    gender: 'Femme',
    race: ['Humain'],
    affiliation: 'Karakura',
    abilities: ['Shun Shun Rikka'],
    position: 'Aucune',
    introduction_arc: 'Agent of the Shinigami',
  },
  {
    id: 11,
    image_url: '',
    name: 'Kisuke Urahara',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Urahara Shop',
    abilities: ['Shikai', 'Bankai'],
    position: '12ème Division',
    introduction_arc: 'Agent of the Shinigami',
  },
  {
    id: 12,
    image_url: '',
    name: 'Yoruichi Shihōin',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Urahara Shop',
    abilities: ['Shunkō'],
    position: '2ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 13,
    image_url: '',
    name: 'Grimmjow Jaegerjaquez',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Sexta Espada',
    introduction_arc: 'Arrancar',
  },
  {
    id: 14,
    image_url: '',
    name: 'Ulquiorra Cifer',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección', 'Segunda Etapa'],
    position: 'Cuatro Espada',
    introduction_arc: 'Arrancar',
  },
  {
    id: 15,
    image_url: '',
    name: 'Shinji Hirako',
    gender: 'Homme',
    race: ['Shinigami', 'Visored'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai', 'Hollowfication'],
    position: '5ème Division',
    introduction_arc: 'Arrancar',
  },
  {
    id: 16,
    image_url: '',
    name: 'Rangiku Matsumoto',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '10ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 17,
    image_url: '',
    name: 'Shunsui Kyōraku',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '1ère Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 18,
    image_url: '',
    name: 'Kaname Tōsen',
    gender: 'Homme',
    race: ['Shinigami', 'Visored'],
    affiliation: "Armée d'Aizen",
    abilities: ['Shikai', 'Bankai', 'Resurrección'],
    position: '9ème Division',
    introduction_arc: 'Soul Society',
  },
  {
    id: 19,
    image_url: '',
    name: 'Yhwach',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['The Almighty', 'Schrift'],
    position: 'Aucune',
    introduction_arc: 'Thousand-Year Blood War',
  },
  {
    id: 20,
    image_url: '',
    name: 'Mayuri Kurotsuchi',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '12ème Division',
    introduction_arc: 'Soul Society',
  },
];