export type Character = {
  id: number;
  image_url: string;
  name: string;
  gender: 'Homme' | 'Femme';
  race: string[];
  affiliation: string;
  abilities: string[];
  position: string;
  introduction_arc: string;
  status: 'Vivant' | 'Décédé' | 'Scellé';
};

export const characters: Character[] = [
  // ==========================================
  // ARC DU SHINIGAMI REMPLAÇANT (IDs 1-12)
  // ==========================================
  {
    id: 1,
    image_url: '/img/ichigo.jpg',
    name: 'Ichigo Kurosaki',
    gender: 'Homme',
    race: ['Humain', 'Shinigami', 'Quincy', 'Hollow', 'Fullbringer'],
    affiliation: 'Karakura',
    abilities: ['Shikai', 'Bankai', 'Hollowfication', 'Fullbring', 'Blut'],
    position: 'Shinigami Remplaçant',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 2,
    image_url: '/img/rukia.jpg',
    name: 'Rukia Kuchiki',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '13ème Division',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 3,
    image_url: '/img/orihime.jpg',
    name: 'Orihime Inoue',
    gender: 'Femme',
    race: ['Humain'],
    affiliation: 'Karakura',
    abilities: ['Shun Shun Rikka'],
    position: 'Aucune',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 4,
    image_url: '/img/uryu.jpg',
    name: 'Uryū Ishida',
    gender: 'Homme',
    race: ['Quincy', 'Humain'],
    affiliation: 'Karakura',
    abilities: ['Letzt Stil', 'Vollständig', 'Schrift'],
    position: 'Sternritter A',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 5,
    image_url: '/img/chad.jpg',
    name: 'Yasutora Sado',
    gender: 'Homme',
    race: ['Humain', 'Fullbringer'],
    affiliation: 'Karakura',
    abilities: ['Fullbring'],
    position: 'Aucune',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 6,
    image_url: '/img/urahara.jpg',
    name: 'Kisuke Urahara',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Urahara Shop',
    abilities: ['Shikai', 'Bankai'],
    position: '12ème Division',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 7,
    image_url: '/img/yoruichi.jpg',
    name: 'Yoruichi Shihōin',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Urahara Shop',
    abilities: ['Shunkō'],
    position: '2ème Division',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 8,
    image_url: '/img/kon.jpg',
    name: 'Kon',
    gender: 'Homme',
    race: ['Âme Modifiée'],
    affiliation: 'Karakura',
    abilities: ['Corps de Peluche'],
    position: 'Aucune',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 9,
    image_url: '/img/isshin.jpg',
    name: 'Isshin Kurosaki',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Karakura',
    abilities: ['Shikai', 'Bankai'],
    position: '10ème Division',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 10,
    image_url: '/img/ryuken.jpg',
    name: 'Ryūken Ishida',
    gender: 'Homme',
    race: ['Quincy', 'Humain'],
    affiliation: 'Karakura',
    abilities: ['Letzt Stil'],
    position: 'Aucune',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 11,
    image_url: '/img/zangetsu.jpg',
    name: 'Zangetsu',
    gender: 'Homme',
    race: ['Zanpakutō', 'Hollow', 'Quincy'],
    affiliation: 'Karakura',
    abilities: ['Shikai', 'Bankai'],
    position: 'Esprit de Zanpakutō',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Vivant',
  },
  {
    id: 12,
    image_url: '/img/masaki.jpg',
    name: 'Masaki Kurosaki',
    gender: 'Femme',
    race: ['Quincy', 'Humain'],
    affiliation: 'Karakura',
    abilities: ['Blut'],
    position: 'Aucune',
    introduction_arc: 'Arc du Shinigami Remplaçant',
    status: 'Décédé',
  },

  // ==========================================
  // ARC DE LA SOUL SOCIETY (IDs 13-40)
  // ==========================================
  {
    id: 13,
    image_url: '/img/kukaku.jpg',
    name: 'Kūkaku Shiba',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Clan Shiba',
    abilities: ['Kidō'],
    position: 'Chef du Clan Shiba',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 14,
    image_url: '/img/ganju.jpg',
    name: 'Ganju Shiba',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Clan Shiba',
    abilities: ['Kidō'],
    position: 'Membre Clan Shiba',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 15,
    image_url: '/img/yamamoto.jpg',
    name: 'Genryūsai Shigekuni Yamamoto',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '1ère Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },
  {
    id: 16,
    image_url: '/img/chojiro.jpg',
    name: 'Chōjirō Sasakibe',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '1ère Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },
  {
    id: 17,
    image_url: '/img/soifon.jpg',
    name: 'Soi Fon',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai', 'Shunkō'],
    position: '2ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 18,
    image_url: '/img/gin.jpg',
    name: 'Gin Ichimaru',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: "Armée d'Aizen",
    abilities: ['Shikai', 'Bankai'],
    position: '3ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },
  {
    id: 19,
    image_url: '/img/kira.jpg',
    name: 'Izuru Kira',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '3ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 20,
    image_url: '/img/unohana.jpg',
    name: 'Retsu Unohana',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '4ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },
  {
    id: 21,
    image_url: '/img/aizen.jpg',
    name: 'Sōsuke Aizen',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: "Armée d'Aizen",
    abilities: ['Shikai', 'Hōgyoku'],
    position: '5ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Scellé',
  },
  {
    id: 22,
    image_url: '/img/hinamori.jpg',
    name: 'Momo Hinamori',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '5ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 23,
    image_url: '/img/byakuya.jpg',
    name: 'Byakuya Kuchiki',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '6ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 24,
    image_url: '/img/renji.jpg',
    name: 'Renji Abarai',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '6ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 25,
    image_url: '/img/komamura.jpg',
    name: 'Sajin Komamura',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '7ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 26,
    image_url: '/img/tetsuzaemon.jpg',
    name: 'Tetsuzaemon Iba',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '7ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 27,
    image_url: '/img/shunsui.jpg',
    name: 'Shunsui Kyōraku',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '1ère Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 28,
    image_url: '/img/nanao.jpg',
    name: 'Nanao Ise',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Kidō'],
    position: '8ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 29,
    image_url: '/img/tosen.jpg',
    name: 'Kaname Tōsen',
    gender: 'Homme',
    race: ['Shinigami', 'Visored'],
    affiliation: "Armée d'Aizen",
    abilities: ['Shikai', 'Bankai', 'Resurrección'],
    position: '9ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },
  {
    id: 30,
    image_url: '/img/hisagi.jpg',
    name: 'Shūhei Hisagi',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '9ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 31,
    image_url: '/img/toshiro.jpg',
    name: 'Tōshirō Hitsugaya',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '10ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 32,
    image_url: '/img/rangiku.jpg',
    name: 'Rangiku Matsumoto',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '10ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 33,
    image_url: '/img/zaraki.jpg',
    name: 'Kenpachi Zaraki',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '11ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 34,
    image_url: '/img/yachiru.jpg',
    name: 'Yachiru Kusajishi',
    gender: 'Femme',
    race: ['Shinigami', 'Zanpakutō'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '11ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 35,
    image_url: '/img/ikkaku.jpg',
    name: 'Ikkaku Madarame',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '11ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 36,
    image_url: '/img/yumichika.jpg',
    name: 'Yumichika Ayasegawa',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '11ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 37,
    image_url: '/img/mayuri.jpg',
    name: 'Mayuri Kurotsuchi',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '12ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Vivant',
  },
  {
    id: 38,
    image_url: '/img/nemu.jpg',
    name: 'Nemu Kurotsuchi',
    gender: 'Femme',
    race: ['Shinigami', 'Âme Modifiée'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '12ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },
  {
    id: 39,
    image_url: '/img/ukitake.jpg',
    name: 'Jūshirō Ukitake',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai'],
    position: '13ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },
  {
    id: 40,
    image_url: '/img/kaien.jpg',
    name: 'Kaien Shiba',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai'],
    position: '13ème Division',
    introduction_arc: 'Arc de la Soul Society',
    status: 'Décédé',
  },

  // ==========================================
  // ARC DE HUECO MUNDO (IDs 41-46 & 50-54)
  // ARC DE LA BATAILLE DE KARAKURA (IDs 47-49)
  // ==========================================
  {
    id: 41,
    image_url: '/img/shinji.jpg',
    name: 'Shinji Hirako',
    gender: 'Homme',
    race: ['Shinigami', 'Visored'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai', 'Hollowfication'],
    position: '5ème Division',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Vivant',
  },
  {
    id: 42,
    image_url: '/img/kensei.jpg',
    name: 'Kensei Muguruma',
    gender: 'Homme',
    race: ['Shinigami', 'Visored'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai', 'Hollowfication'],
    position: '9ème Division',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Vivant',
  },
  {
    id: 43,
    image_url: '/img/rose.jpg',
    name: 'Rōjūrō Ōtoribashi',
    gender: 'Homme',
    race: ['Shinigami', 'Visored'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Bankai', 'Hollowfication'],
    position: '3ème Division',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Vivant',
  },
  {
    id: 44,
    image_url: '/img/hiyori.jpg',
    name: 'Hiyori Sarugaki',
    gender: 'Femme',
    race: ['Shinigami', 'Visored'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Hollowfication'],
    position: '12ème Division',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Vivant',
  },
  {
    id: 45,
    image_url: '/img/love.jpg',
    name: 'Love Aikawa',
    gender: 'Homme',
    race: ['Shinigami', 'Visored'],
    affiliation: 'Gotei 13',
    abilities: ['Shikai', 'Hollowfication'],
    position: '7ème Division',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Vivant',
  },
  {
    id: 46,
    image_url: '/img/yammy.jpg',
    name: 'Yammy Llargo',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Cero Espada',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Décédé',
  },
  {
    id: 47,
    image_url: '/img/starrk.jpg',
    name: 'Coyote Starrk',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Primera Espada',
    introduction_arc: 'Arc de la Bataille de Karakura',
    status: 'Décédé',
  },
  {
    id: 48,
    image_url: '/img/barragan.jpg',
    name: 'Barragan Louisenbairn',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Segunda Espada',
    introduction_arc: 'Arc de la Bataille de Karakura',
    status: 'Décédé',
  },
  {
    id: 49,
    image_url: '/img/harribel.jpg',
    name: 'Tier Harribel',
    gender: 'Femme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Tres Espada',
    introduction_arc: 'Arc de la Bataille de Karakura',
    status: 'Vivant',
  },
  {
    id: 50,
    image_url: '/img/nelliel.jpg',
    name: 'Nelliel Tu Odelschwanck',
    gender: 'Femme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Tres Espada',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Vivant',
  },
  {
    id: 51,
    image_url: '/img/ulquiorra.jpg',
    name: 'Ulquiorra Cifer',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección', 'Segunda Etapa'],
    position: 'Cuatro Espada',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Décédé',
  },
  {
    id: 52,
    image_url: '/img/nnoitra.jpg',
    name: 'Nnoitra Gilga',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Quinto Espada',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Décédé',
  },
  {
    id: 53,
    image_url: '/img/grimmjow.jpg',
    name: 'Grimmjow Jaegerjaquez',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Sexta Espada',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Vivant',
  },
  {
    id: 54,
    image_url: '/img/szayelaporro.jpg',
    name: 'Szayelaporro Granz',
    gender: 'Homme',
    race: ['Arrancar'],
    affiliation: "Armée d'Aizen",
    abilities: ['Resurrección'],
    position: 'Octava Espada',
    introduction_arc: 'Arc de Hueco Mundo',
    status: 'Décédé',
  },

  // ==========================================
  // ARC DES FULLBRINGERS (IDs 55-58)
  // ==========================================
  {
    id: 55,
    image_url: '/img/ginjo.jpg',
    name: 'Kūgo Ginjō',
    gender: 'Homme',
    race: ['Humain', 'Shinigami', 'Fullbringer'],
    affiliation: 'Xcution',
    abilities: ['Fullbring', 'Bankai'],
    position: 'Leader Xcution',
    introduction_arc: 'Arc des Fullbringers',
    status: 'Décédé',
  },
  {
    id: 56,
    image_url: '/img/tsukishima.jpg',
    name: 'Shūkurō Tsukishima',
    gender: 'Homme',
    race: ['Humain', 'Fullbringer'],
    affiliation: 'Xcution',
    abilities: ['Fullbring'],
    position: 'Membre Xcution',
    introduction_arc: 'Arc des Fullbringers',
    status: 'Décédé',
  },
  {
    id: 57,
    image_url: '/img/riruka.jpg',
    name: 'Riruka Dokugamine',
    gender: 'Femme',
    race: ['Humain', 'Fullbringer'],
    affiliation: 'Xcution',
    abilities: ['Fullbring'],
    position: 'Membre Xcution',
    introduction_arc: 'Arc des Fullbringers',
    status: 'Vivant',
  },
  {
    id: 58,
    image_url: '/img/yukio.jpg',
    name: 'Yukio Hans Vorarlberna',
    gender: 'Homme',
    race: ['Humain', 'Fullbringer'],
    affiliation: 'Xcution',
    abilities: ['Fullbring'],
    position: 'Membre Xcution',
    introduction_arc: 'Arc des Fullbringers',
    status: 'Vivant',
  },

  // ==========================================
  // ARC DE LA GUERRE SANGLANTE DE MILLE ANS (TYBW) (IDs 59-72)
  // ==========================================
  {
    id: 59,
    image_url: '/img/soulking.jpg',
    name: 'Roi des Esprits',
    gender: 'Homme',
    race: ['Divinité'],
    affiliation: 'Soul Society',
    abilities: ['The Almighty'],
    position: 'Roi des Esprits',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Scellé',
  },
  {
    id: 60,
    image_url: '/img/ichibe.jpg',
    name: 'Ichibē Hyōsube',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Division 0',
    abilities: ['Shikai', 'Bankai'],
    position: "Moine d'œil",
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Vivant',
  },
  {
    id: 61,
    image_url: '/img/oetsu.jpg',
    name: 'Ōetsu Nimaiya',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Division 0',
    abilities: ['Shikai'],
    position: 'Dieu du Sabre',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Vivant',
  },
  {
    id: 62,
    image_url: '/img/tenjiro.jpg',
    name: 'Tenjirō Kirinji',
    gender: 'Homme',
    race: ['Shinigami'],
    affiliation: 'Division 0',
    abilities: ['Shikai'],
    position: 'Démon des Sources Chaudes',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Vivant',
  },
  {
    id: 63,
    image_url: '/img/senjumaru.jpg',
    name: 'Senjumaru Shutara',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Division 0',
    abilities: ['Shikai', 'Bankai'],
    position: 'Grand Tisserand',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Vivant',
  },
  {
    id: 64,
    image_url: '/img/kirio.jpg',
    name: 'Kirio Hikifune',
    gender: 'Femme',
    race: ['Shinigami'],
    affiliation: 'Division 0',
    abilities: ['Shikai'],
    position: 'Souverain des Céréales',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Vivant',
  },
  {
    id: 65,
    image_url: '/img/yhwach.jpg',
    name: 'Yhwach',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['The Almighty', 'Schrift'],
    position: 'Aucune',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
  {
    id: 66,
    image_url: '/img/haschwalth.jpg',
    name: 'Jugram Haschwalth',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['Schrift'],
    position: 'Sternritter B',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
  {
    id: 67,
    image_url: '/img/lille.jpg',
    name: 'Lille Barro',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['Schrift', 'Vollständig'],
    position: 'Schutzstaffel',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
  {
    id: 68,
    image_url: '/img/gerard.jpg',
    name: 'Gerard Valkyrie',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['Schrift', 'Vollständig'],
    position: 'Schutzstaffel',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
  {
    id: 69,
    image_url: '/img/pernida.jpg',
    name: 'Pernida Parnkgjas',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['Schrift'],
    position: 'Schutzstaffel',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
  {
    id: 70,
    image_url: '/img/askin.jpg',
    name: 'Askin Nakk Le Vaar',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['Schrift', 'Vollständig'],
    position: 'Schutzstaffel',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
  {
    id: 71,
    image_url: '/img/bazzb.jpg',
    name: 'Bazz-B',
    gender: 'Homme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['Schrift'],
    position: 'Sternritter H',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
  {
    id: 72,
    image_url: '/img/bambietta.jpg',
    name: 'Bambietta Basterbine',
    gender: 'Femme',
    race: ['Quincy'],
    affiliation: 'Wandenreich',
    abilities: ['Schrift', 'Vollständig'],
    position: 'Sternritter E',
    introduction_arc: 'Arc de la Guerre Sanglante de Mille Ans (Thousand-Year Blood War)',
    status: 'Décédé',
  },
];