export type CharacterPublic = {
  id: number;
  name: string;
  image_url: string;
};

export const charactersPublic: CharacterPublic[] = [
  { id: 1, name: "Ichigo Kurosaki", image_url: "/img/ichigo.jpg" },
  { id: 2, name: "Rukia Kuchiki", image_url: "/img/rukia.jpg" },
  { id: 3, name: "Orihime Inoue", image_url: "/img/orihime.jpg" },
  { id: 4, name: "Uryū Ishida", image_url: "/img/uryu.jpg" },
  { id: 5, name: "Yasutora Sado", image_url: "/img/chad.jpg" },
  { id: 6, name: "Kisuke Urahara", image_url: "/img/urahara.jpg" },
  { id: 7, name: "Yoruichi Shihōin", image_url: "/img/yoruichi.jpg" },
  { id: 8, name: "Kon", image_url: "/img/kon.jpg" },
  { id: 9, name: "Isshin Kurosaki", image_url: "/img/isshin.jpg" },
  { id: 10, name: "Ryūken Ishida", image_url: "/img/ryuken.jpg" },
  { id: 11, name: "Zangetsu", image_url: "/img/zangetsu.jpg" },
  { id: 12, name: "Masaki Kurosaki", image_url: "/img/masaki.jpg" },
  { id: 13, name: "Kūkaku Shiba", image_url: "/img/kukaku.jpg" },
  { id: 14, name: "Ganju Shiba", image_url: "/img/ganju.jpg" },
  { id: 15, name: "Genryūsai Shigekuni Yamamoto", image_url: "/img/yamamoto.jpg" },
  { id: 16, name: "Chōjirō Sasakibe", image_url: "/img/chojiro.jpg" },
  { id: 17, name: "Soi Fon", image_url: "/img/soifon.jpg" },
  { id: 18, name: "Gin Ichimaru", image_url: "/img/gin.jpg" },
  { id: 19, name: "Izuru Kira", image_url: "/img/kira.jpg" },
  { id: 20, name: "Retsu Unohana", image_url: "/img/unohana.jpg" },
  { id: 21, name: "Sōsuke Aizen", image_url: "/img/aizen.jpg" },
  { id: 22, name: "Momo Hinamori", image_url: "/img/hinamori.jpg" },
  { id: 23, name: "Byakuya Kuchiki", image_url: "/img/byakuya.jpg" },
  { id: 24, name: "Renji Abarai", image_url: "/img/renji.jpg" },
  { id: 25, name: "Sajin Komamura", image_url: "/img/komamura.jpg" },
  { id: 26, name: "Tetsuzaemon Iba", image_url: "/img/tetsuzaemon.jpg" },
  { id: 27, name: "Shunsui Kyōraku", image_url: "/img/shunsui.jpg" },
  { id: 28, name: "Nanao Ise", image_url: "/img/nanao.jpg" },
  { id: 29, name: "Kaname Tōsen", image_url: "/img/tosen.jpg" },
  { id: 30, name: "Shūhei Hisagi", image_url: "/img/hisagi.jpg" },
  { id: 31, name: "Tōshirō Hitsugaya", image_url: "/img/toshiro.jpg" },
  { id: 32, name: "Rangiku Matsumoto", image_url: "/img/rangiku.jpg" },
  { id: 33, name: "Kenpachi Zaraki", image_url: "/img/zaraki.jpg" },
  { id: 34, name: "Yachiru Kusajishi", image_url: "/img/yachiru.jpg" },
  { id: 35, name: "Ikkaku Madarame", image_url: "/img/ikkaku.jpg" },
  { id: 36, name: "Yumichika Ayasegawa", image_url: "/img/yumichika.jpg" },
  { id: 37, name: "Mayuri Kurotsuchi", image_url: "/img/mayuri.jpg" },
  { id: 38, name: "Nemu Kurotsuchi", image_url: "/img/nemu.jpg" },
  { id: 39, name: "Jūshirō Ukitake", image_url: "/img/ukitake.jpg" },
  { id: 40, name: "Kaien Shiba", image_url: "/img/kaien.jpg" },
  { id: 41, name: "Shinji Hirako", image_url: "/img/shinji.jpg" },
  { id: 42, name: "Kensei Muguruma", image_url: "/img/kensei.jpg" },
  { id: 43, name: "Rōjūrō Ōtoribashi", image_url: "/img/rose.jpg" },
  { id: 44, name: "Hiyori Sarugaki", image_url: "/img/hiyori.jpg" },
  { id: 45, name: "Love Aikawa", image_url: "/img/love.jpg" },
  { id: 46, name: "Yammy Llargo", image_url: "/img/yammy.jpg" },
  { id: 47, name: "Coyote Starrk", image_url: "/img/starrk.jpg" },
  { id: 48, name: "Barragan Louisenbairn", image_url: "/img/barragan.jpg" },
  { id: 49, name: "Tier Harribel", image_url: "/img/harribel.jpg" },
  { id: 50, name: "Nelliel Tu Odelschwanck", image_url: "/img/nelliel.jpg" },
  { id: 51, name: "Ulquiorra Cifer", image_url: "/img/ulquiorra.jpg" },
  { id: 52, name: "Nnoitra Gilga", image_url: "/img/nnoitra.jpg" },
  { id: 53, name: "Grimmjow Jaegerjaquez", image_url: "/img/grimmjow.jpg" },
  { id: 54, name: "Szayelaporro Granz", image_url: "/img/szayelaporro.jpg" },
  { id: 55, name: "Kūgo Ginjō", image_url: "/img/ginjo.jpg" },
  { id: 56, name: "Shūkurō Tsukishima", image_url: "/img/tsukishima.jpg" },
  { id: 57, name: "Riruka Dokugamine", image_url: "/img/riruka.jpg" },
  { id: 58, name: "Yukio Hans Vorarlberna", image_url: "/img/yukio.jpg" },
  { id: 59, name: "Roi des Esprits", image_url: "/img/soulking.jpg" },
  { id: 60, name: "Ichibē Hyōsube", image_url: "/img/ichibe.jpg" },
  { id: 61, name: "Ōetsu Nimaiya", image_url: "/img/oetsu.jpg" },
  { id: 62, name: "Tenjirō Kirinji", image_url: "/img/tenjiro.jpg" },
  { id: 63, name: "Senjumaru Shutara", image_url: "/img/senjumaru.jpg" },
  { id: 64, name: "Kirio Hikifune", image_url: "/img/kirio.jpg" },
  { id: 65, name: "Yhwach", image_url: "/img/yhwach.jpg" },
  { id: 66, name: "Jugram Haschwalth", image_url: "/img/haschwalth.jpg" },
  { id: 67, name: "Lille Barro", image_url: "/img/lille.jpg" },
  { id: 68, name: "Gerard Valkyrie", image_url: "/img/gerard.jpg" },
  { id: 69, name: "Pernida Parnkgjas", image_url: "/img/pernida.jpg" },
  { id: 70, name: "Askin Nakk Le Vaar", image_url: "/img/askin.jpg" },
  { id: 71, name: "Bazz-B", image_url: "/img/bazzb.jpg" },
  { id: 72, name: "Bambietta Basterbine", image_url: "/img/bambietta.jpg" }
];
